version: '3'

services:
  api:
    build: .
    ports:
      - "5700:80"
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/gmessages
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: mvertes/alpine-mongo